# Generated by Django 3.2 on 2022-09-15 18:30

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import interests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_on_list', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, upload_to='thumbnail-region')),
                ('sidebar', models.TextField(blank=True)),
                ('ad_manager', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('logo_on_navbar', models.ImageField(blank=True, max_length=255, upload_to='logo-on-navbar/')),
                ('listing_title1', models.CharField(blank=True, max_length=255)),
                ('carousel_title', models.CharField(blank=True, max_length=255)),
                ('display_on_navbar', models.BooleanField(default=True)),
                ('display_list', models.BooleanField(default=True)),
                ('display_billboard', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('list_carousel', models.ManyToManyField(blank=True, to='list.Category')),
                ('logo_on_navbar2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar2', to=settings.FILER_IMAGE_MODEL)),
                ('region_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interests.region')),
                ('thumbnail2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail2', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('custom_overlay', models.ImageField(blank=True, max_length=255, upload_to='custom-rating/')),
                ('google_map', models.TextField(blank=True)),
                ('location_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cuisine_url', models.URLField(blank=True)),
                ('cuisine', models.CharField(blank=True, max_length=255)),
                ('pricing_category_url', models.URLField(blank=True)),
                ('pricing_category', models.CharField(blank=True, max_length=255)),
                ('seating', models.CharField(blank=True, max_length=255)),
                ('chef_url', models.URLField(blank=True)),
                ('chef', models.CharField(blank=True, max_length=255)),
                ('opening_hours', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, max_length=255, upload_to='img/%Y/%m/')),
                ('sidebar', models.TextField(blank=True)),
                ('ad_manager', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('carousel_title', models.CharField(blank=True, max_length=255)),
                ('top_slider', models.BooleanField(default=False)),
                ('cover_slider', models.BooleanField(default=False)),
                ('hide_rating', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=True)),
                ('display_list', models.BooleanField(default=True)),
                ('display_billboard', models.BooleanField(default=True)),
                ('filter_tags', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('email1', models.EmailField(blank=True, max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('web_text', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('isvalidated', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('custom_overlay2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_overlay2', to=settings.FILER_IMAGE_MODEL)),
                ('list_carousel', models.ManyToManyField(blank=True, to='list.Category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interests.region')),
                ('regions', models.ManyToManyField(blank=True, related_name='regions', to='interests.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='yard-image/')),
                ('image2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('title', models.CharField(max_length=255)),
                ('review', models.TextField(validators=[interests.models.review_validator])),
                ('value', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('service', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('cleanliness', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('location', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('sustainability', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_images', models.ImageField(blank=True, max_length=255, upload_to='region-image/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.region')),
                ('region_images2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='yard-cover-image/')),
                ('image2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(validators=[interests.models.review_validator])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('rr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interests.reviewandrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
