# Generated by Django 3.2 on 2022-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='navbar_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
