# Generated by Django 3.2 on 2022-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_region_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='navbar_order',
            field=models.IntegerField(unique=True),
        ),
    ]
