# Generated by Django 3.2 on 2023-01-05 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('list', '0002_post_date_created'),
        ('filters', '0005_auto_20221121_2152'),
        ('interests', '0003_alter_region_navbar_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Interest',
        ),
    ]
