# Generated by Django 3.2 on 2023-01-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0004_rename_restaurant_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Restaurant'},
        ),
        migrations.RenameField(
            model_name='coversliderimage',
            old_name='restaurant',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='reviewandrating',
            old_name='restaurant',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='topsliderimage',
            old_name='restaurant',
            new_name='interest',
        ),
    ]
