# Generated by Django 3.2 on 2023-02-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0008_interest_logo_on_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coversliderimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='custom_overlay',
        ),
        migrations.RemoveField(
            model_name='region',
            name='logo_on_navbar',
        ),
        migrations.RemoveField(
            model_name='region',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='regionimage',
            name='region_images',
        ),
        migrations.RemoveField(
            model_name='topsliderimage',
            name='image',
        ),
    ]
