# Generated by Django 3.2 on 2023-02-22 11:47

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('interests', '0009_auto_20230220_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coversliderimage',
            old_name='image2',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='regionimage',
            old_name='region_images2',
            new_name='region_images',
        ),
        migrations.RenameField(
            model_name='topsliderimage',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='custom_overlay2',
        ),
        migrations.RemoveField(
            model_name='region',
            name='logo_on_navbar2',
        ),
        migrations.RemoveField(
            model_name='region',
            name='thumbnail2',
        ),
        migrations.AddField(
            model_name='interest',
            name='custom_overlay',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_overlay+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
