# Generated by Django 3.2 on 2023-03-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0010_auto_20230222_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.region'),
        ),
    ]
