# Generated by Django 3.2 on 2023-03-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0011_alter_interest_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='location',
            new_name='info1',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='location_url',
            new_name='info1_url',
        ),
    ]
