# Generated by Django 3.2 on 2023-03-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0012_auto_20230313_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='cuisine',
            new_name='info2',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='cuisine_url',
            new_name='info2_url',
        ),
    ]
