# Generated by Django 3.2 on 2023-03-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0013_auto_20230313_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='pricing_category',
            new_name='info3',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='pricing_category_url',
            new_name='info3_url',
        ),
    ]
