# Generated by Django 3.2 on 2023-03-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0015_auto_20230313_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='chef',
            new_name='info5',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='chef_url',
            new_name='info5_url',
        ),
    ]
