# Generated by Django 3.2 on 2023-03-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0018_auto_20230313_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='interests.region'),
        ),
    ]
