# Generated by Django 3.2 on 2023-03-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0020_auto_20230324_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='web_text2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='website2',
            field=models.CharField(blank=True, max_length=255, verbose_name='ReservationURL'),
        ),
    ]
