# Generated by Django 3.2 on 2023-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0021_auto_20230327_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='display_list',
            field=models.BooleanField(default=True, verbose_name='Display Carousel'),
        ),
        migrations.AlterField(
            model_name='region',
            name='display_list',
            field=models.BooleanField(default=True, verbose_name='Display Carousel'),
        ),
    ]
