# Generated by Django 3.2 on 2023-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0022_auto_20230715_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
