# Generated by Django 3.2 on 2023-07-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0024_auto_20230721_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='filter_tags',
            new_name='linkup_tags',
        ),
    ]
