# Generated by Django 3.2 on 2024-01-11 10:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('interests', '0025_rename_filter_tags_interest_linkup_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='cover2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='custom_overlay',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_overlay+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_on_navbar+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_on_navbar+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='regionimage',
            name='region_images',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='topsliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
