# Generated by Django 3.2 on 2024-03-12 16:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('interests', '0026_auto_20240111_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='cover2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='custom_overlay',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_overlay+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='description_on_list',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='regionimage',
            name='region_images',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='topsliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
