# Generated by Django 3.2 on 2024-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0028_auto_20240313_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geo_filters',
            field=models.CharField(choices=[('WORLD', 'World'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('LOCAL', 'Local'), ('CITY', 'City'), ('NONE', 'None')], default='WORLD', max_length=20),
        ),
    ]
