# Generated by Django 3.2 on 2024-05-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0029_alter_region_geo_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ('name',), 'verbose_name': 'Restaurant'},
        ),
    ]
