# Generated by Django 3.2 on 2024-06-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('WORLD', 'World'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('LOCAL', 'Local'), ('CITY', 'City'), ('FACILITY', 'Inside'), ('SERVICE', 'Services'), ('RATING', 'Awards'), ('SP1', 'Cuisine'), ('SP2', 'Style'), ('SP3', 'Pricing')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='interest_filter', to='interests.Interest')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.filter')),
            ],
            options={
                'ordering': ('types', 'name'),
            },
        ),
    ]
