# Generated by Django 3.2 on 2022-10-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_alter_region_navbar_order'),
        ('filters', '0002_auto_20220919_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CulinaryRegion',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='WorldRegion',
            new_name='World',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Destination'},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Cuisine'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Inside'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Award'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'X'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'verbose_name': 'Region'},
        ),
    ]
