# Generated by Django 3.2 on 2022-10-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_alter_region_navbar_order'),
        ('filters', '0003_auto_20221023_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='city_filter', to='interests.Restaurant')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='SP1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='sp1_filter', to='interests.Restaurant')),
            ],
            options={
                'verbose_name': 'Cuisine',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Inside', 'verbose_name_plural': 'Insides'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Cuisine Region'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.RemoveField(
            model_name='world',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='country_filter', to='interests.Restaurant'),
        ),
        migrations.AddField(
            model_name='world',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='world_filter', to='interests.Restaurant'),
        ),
        migrations.AlterField(
            model_name='region',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='region_filter', to='interests.Restaurant'),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
