# Generated by Django 3.2 on 2022-11-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_auto_20221030_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Inside', 'verbose_name_plural': 'Inside'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisine'},
        ),
        migrations.AlterModelOptions(
            name='sp1',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Style'},
        ),
    ]
