# Generated by Django 3.2 on 2023-01-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_auto_20230105_1956'),
        ('filters', '0006_auto_20230105_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interests', models.ManyToManyField(blank=True, related_name='sp2_filter', to='interests.Interest')),
            ],
            options={
                'verbose_name': 'SP2',
            },
        ),
    ]
