# Generated by Django 3.2 on 2023-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_sp2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='sp1',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisine'},
        ),
        migrations.AlterModelOptions(
            name='sp2',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Style'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'verbose_name': 'World'},
        ),
    ]
