# Generated by Django 3.2 on 2023-07-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0024_auto_20230721_1938'),
        ('filters', '0009_auto_20230313_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interests', models.ManyToManyField(blank=True, related_name='sp3_filter', to='interests.Interest')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
            },
        ),
    ]
