# Generated by Django 3.2 on 2023-07-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0010_sp3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Inside', 'verbose_name_plural': 'Inside'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['name'], 'verbose_name': 'Awards', 'verbose_name_plural': 'Award'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Services', 'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='sp1',
            options={'ordering': ['name'], 'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisine'},
        ),
        migrations.AlterModelOptions(
            name='sp2',
            options={'ordering': ['name'], 'verbose_name': 'Style', 'verbose_name_plural': 'Style'},
        ),
        migrations.AlterModelOptions(
            name='sp3',
            options={'ordering': ['name'], 'verbose_name': 'Pricing', 'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['name'], 'verbose_name': 'World', 'verbose_name_plural': 'World'},
        ),
    ]
