# Generated by Django 3.2 on 2024-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0028_auto_20240313_1450'),
        ('filters', '0011_auto_20230729_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('WORLD', 'World'), ('COUNTRY', 'Destination'), ('REGION', 'Region'), ('CITY', 'City'), ('FACILITY', 'Inside'), ('SERVICE', 'Services'), ('RATING', 'Awards'), ('SP1', 'Cuisine'), ('SP2', 'Style'), ('SP3', 'Pricing')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='interest_filter', to='interests.Interest')),
            ],
        ),
    ]
