# Generated by Django 3.2 on 2024-05-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0013_auto_20240504_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.filter'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='types',
            field=models.CharField(choices=[('WORLD', 'World'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('LOCAL', 'Local'), ('CITY', 'City'), ('FACILITY', 'Inside'), ('SERVICE', 'Services'), ('RATING', 'Awards'), ('SP1', 'Cuisine'), ('SP2', 'Style'), ('SP3', 'Pricing')], max_length=20),
        ),
    ]
