# Generated by Django 3.2 on 2023-02-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_billboard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='image2',
            new_name='image',
        ),
    ]
