# Generated by Django 3.2 on 2023-03-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_rename_image2_billboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='open_in_new_window',
            field=models.BooleanField(default=True),
        ),
    ]
