# Generated by Django 3.2 on 2023-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_billboard_open_in_new_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_list',
            field=models.BooleanField(default=True, verbose_name='Display Carousel'),
        ),
    ]
