# Generated by Django 3.2 on 2024-03-12 16:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('list', '0007_alter_billboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
