# Generated by Django 3.2 on 2024-06-01 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filters', '0001_initial'),
        ('interests', '0001_initial'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('LIST', 'List'), ('POST', 'Post'), ('WITHOUT_SIDEBAR', 'Without Sidebar'), ('LINKUP', 'Linkup'), ('FILTER', 'Filter')], max_length=20)),
                ('geo_filters', models.CharField(choices=[('WORLD', 'World'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('LOCAL', 'Local'), ('CITY', 'City'), ('NONE', 'None')], default='WORLD', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Header Content')),
                ('additional_content', tinymce.models.HTMLField(blank=True, verbose_name='Main Content')),
                ('content_on_list', tinymce.models.HTMLField(blank=True, verbose_name='List Content')),
                ('sidebar', models.TextField(blank=True)),
                ('ad_manager', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('filter_title', models.CharField(blank=True, max_length=255, verbose_name='Title Filter List')),
                ('filter_display', models.BooleanField(default=False, verbose_name='Display List Filters')),
                ('listing_title1', models.CharField(blank=True, max_length=255, verbose_name='Title Region List')),
                ('show_listing1', models.BooleanField(default=False, verbose_name='Display List Regions')),
                ('listing_title2', models.CharField(blank=True, max_length=255, verbose_name='Title Post List')),
                ('show_listing2', models.BooleanField(default=False, verbose_name='Display List Posts')),
                ('listing_title3', models.CharField(blank=True, max_length=255, verbose_name='Title Section 3')),
                ('show_listing3', models.BooleanField(default=False, verbose_name='Display List3')),
                ('carousel_title', models.CharField(blank=True, max_length=255, verbose_name='Title Carousel')),
                ('display_list', models.BooleanField(default=True, verbose_name='Display Carousel')),
                ('display_billboard', models.BooleanField(default=True, verbose_name='Display Billboards')),
                ('navbar_order', models.IntegerField(unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.ManyToManyField(blank=True, to='interests.Region', verbose_name='List Regions')),
                ('filter_list', models.ManyToManyField(blank=True, to='filters.Filter', verbose_name='List Filters')),
                ('list_carousel', models.ManyToManyField(blank=True, related_name='_pages_app_contentpage_list_carousel_+', to='list.Category', verbose_name='List Carousel')),
                ('list_section', models.ManyToManyField(blank=True, related_name='_pages_app_contentpage_list_section_+', to='list.Category', verbose_name='List Posts')),
                ('logo_on_navbar', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_on_navbar', to=settings.FILER_IMAGE_MODEL)),
                ('page_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages_app.contentpage')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'ordering': ('types', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('new_window', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('script', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar', models.TextField(blank=True)),
                ('ad_manager', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(unique=True)),
                ('page', models.ManyToManyField(blank=True, to='pages_app.ContentPage')),
                ('region', models.ManyToManyField(blank=True, to='interests.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages_app.contentpage')),
            ],
        ),
    ]
