# Generated by Django 3.2 on 2022-12-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('LIST', 'List'), ('WITHOUT_SIDEBAR', 'Without Sidebar'), ('LINKUP', 'Linkup')], max_length=20),
        ),
    ]
