# Generated by Django 3.2 on 2023-01-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_alter_contentpage_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='geo_filters',
            field=models.CharField(choices=[('ALL', 'All'), ('WORLD', 'World'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('CITY', 'City')], default='ALL', max_length=20),
        ),
    ]
