# Generated by Django 3.2 on 2023-02-13 14:58

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pages_app', '0004_alter_contentpage_geo_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='logo_on_navbar',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
