# Generated by Django 3.2 on 2023-02-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0005_contentpage_logo_on_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
    ]
