# Generated by Django 3.2 on 2023-02-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0006_auto_20230220_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='thumbnail2',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='image2',
            new_name='image',
        ),
    ]
