# Generated by Django 3.2 on 2023-05-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0007_auto_20230222_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
