# Generated by Django 3.2 on 2023-06-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0008_footer_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='page_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages_app.contentpage'),
        ),
    ]
