# Generated by Django 3.2 on 2023-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0009_contentpage_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='navbar_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
