# Generated by Django 3.2 on 2023-06-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0010_contentpage_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='navbar_order',
            field=models.IntegerField(default=True),
        ),
    ]
