# Generated by Django 3.2 on 2023-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0011_alter_contentpage_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='navbar_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('LIST', 'List'), ('POST', 'Post'), ('WITHOUT_SIDEBAR', 'Without Sidebar'), ('LINKUP', 'Linkup')], max_length=20),
        ),
    ]
