# Generated by Django 3.2 on 2024-05-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0014_auto_20240504_1358'),
        ('pages_app', '0017_alter_contentpage_geo_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='filter_display',
            field=models.BooleanField(default=False, verbose_name='Display List Filters'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='filter_list',
            field=models.ManyToManyField(blank=True, to='filters.Filter', verbose_name='List Filters'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='filter_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title Filter List'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('LIST', 'List'), ('POST', 'Post'), ('WITHOUT_SIDEBAR', 'Without Sidebar'), ('LINKUP', 'Linkup'), ('FILTER', 'Filter')], max_length=20),
        ),
    ]
